import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { Outlet, Link, createRootRouteWithContext, useRouter, HeadContent, Scripts } from "@tanstack/react-router";
import { useEffect, type ReactNode } from "react";
import appCss from "../styles.css?url";
import { reportLovableError } from "../lib/lovable-error-reporting";
import { SiteShell } from "@/components/site-shell";

function NotFoundComponent(){ return <div className="flex min-h-screen items-center justify-center bg-background px-4"><div className="text-center"><p className="eyebrow">Record unavailable</p><h1 className="mt-2 font-display text-6xl font-bold text-primary">404</h1><p className="mt-3 text-muted-foreground">This public record could not be found.</p><Link to="/" className="mt-6 inline-flex rounded-md bg-primary px-4 py-2 font-bold text-primary-foreground">Return home</Link></div></div> }
function ErrorComponent({error,reset}:{error:Error;reset:()=>void}){ const router=useRouter(); useEffect(()=>reportLovableError(error,{boundary:"root"}),[error]); return <div className="flex min-h-screen items-center justify-center"><div className="text-center"><h1 className="font-display text-2xl font-bold">This record did not load</h1><button className="mt-4 rounded-md bg-primary px-4 py-2 text-primary-foreground" onClick={()=>{router.invalidate();reset()}}>Try again</button></div></div> }
export const Route=createRootRouteWithContext<{queryClient:QueryClient}>()({head:()=>({meta:[{charSet:"utf-8"},{name:"viewport",content:"width=device-width, initial-scale=1"},{name:"theme-color",content:"#1b365d"}],links:[{rel:"stylesheet",href:appCss},{rel:"preconnect",href:"https://fonts.googleapis.com"},{rel:"preconnect",href:"https://fonts.gstatic.com",crossOrigin:"anonymous"},{rel:"stylesheet",href:"https://fonts.googleapis.com/css2?family=Merriweather:wght@400;700;900&family=Plus+Jakarta+Sans:wght@400;500;600;700;800&display=swap"},{rel:"icon",href:"/favicon.ico",type:"image/x-icon"}]}),shellComponent:RootShell,component:RootComponent,notFoundComponent:NotFoundComponent,errorComponent:ErrorComponent});
function RootShell({children}:{children:ReactNode}){return <html lang="en"><head><HeadContent/></head><body>{children}<Scripts/></body></html>}
function RootComponent(){const {queryClient}=Route.useRouteContext();return <QueryClientProvider client={queryClient}><SiteShell><Outlet/></SiteShell></QueryClientProvider>}
