/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GramSabhaRouteImport } from './routes/gram-sabha'
import { Route as PanchayatRouteImport } from './routes/panchayat'
import { Route as SocialAuditRouteImport } from './routes/social-audit'
import { Route as VoteRouteImport } from './routes/vote'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GramSabhaRoute = GramSabhaRouteImport.update({
  id: '/gram-sabha',
  path: '/gram-sabha',
  getParentRoute: () => rootRouteImport,
} as any)
const PanchayatRoute = PanchayatRouteImport.update({
  id: '/panchayat',
  path: '/panchayat',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialAuditRoute = SocialAuditRouteImport.update({
  id: '/social-audit',
  path: '/social-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const VoteRoute = VoteRouteImport.update({
  id: '/vote',
  path: '/vote',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gram-sabha': typeof GramSabhaRoute
  '/panchayat': typeof PanchayatRoute
  '/social-audit': typeof SocialAuditRoute
  '/vote': typeof VoteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gram-sabha': typeof GramSabhaRoute
  '/panchayat': typeof PanchayatRoute
  '/social-audit': typeof SocialAuditRoute
  '/vote': typeof VoteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gram-sabha': typeof GramSabhaRoute
  '/panchayat': typeof PanchayatRoute
  '/social-audit': typeof SocialAuditRoute
  '/vote': typeof VoteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/gram-sabha' | '/panchayat' | '/social-audit' | '/vote'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/gram-sabha' | '/panchayat' | '/social-audit' | '/vote'
  id:
    '__root__' | '/' | '/gram-sabha' | '/panchayat' | '/social-audit' | '/vote'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GramSabhaRoute: typeof GramSabhaRoute
  PanchayatRoute: typeof PanchayatRoute
  SocialAuditRoute: typeof SocialAuditRoute
  VoteRoute: typeof VoteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gram-sabha': {
      id: '/gram-sabha'
      path: '/gram-sabha'
      fullPath: '/gram-sabha'
      preLoaderRoute: typeof GramSabhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panchayat': {
      id: '/panchayat'
      path: '/panchayat'
      fullPath: '/panchayat'
      preLoaderRoute: typeof PanchayatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social-audit': {
      id: '/social-audit'
      path: '/social-audit'
      fullPath: '/social-audit'
      preLoaderRoute: typeof SocialAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vote': {
      id: '/vote'
      path: '/vote'
      fullPath: '/vote'
      preLoaderRoute: typeof VoteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GramSabhaRoute: GramSabhaRoute,
  PanchayatRoute: PanchayatRoute,
  SocialAuditRoute: SocialAuditRoute,
  VoteRoute: VoteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
